
### GET request to example server
GET http://localhost:8080/webapi/bakeries


### GET request to example server
GET http://localhost:8080/webapi/bakeries/1


### GET request to example server
GET http://localhost:8080/webapi/products/1/bakeries

### GET request to example server
GET http://localhost:8080/webapi/products

### GET request to example server
GET http://localhost:8080/webapi/products/1

###
POST http://localhost:8080/webapi/bakeries
Content-Type:  application/json
Accept-Language: it

{
  "id": 3,
  "name": " ",
  "logo": "logo.png"
}