### GET all cienmas
GET http://localhost:8070/webapi/cinemas


### GET cinema
GET http://localhost:8070/webapi/movies/1/cinemas
Accept: application/json
### POST new cinema
POST http://localhost:8070/webapi/cinemas
Content-Type: application/json
Accept-Language: it
Authorization: Basic dbuser1 dbuser1

{
"name": "Kinoteka Jeszcze",
"logo": "logo.png"
}
###